#build site:
#  image: node:8
#  stage: build
#  script:
#    - npm install --progress=false
#    - npm run build
#  artifacts:
#    expire_in: 1 week
#    paths:
#     - dist

deploy:
  image: node:10.15.0-stretch
  stage: deploy
  script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -



      ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - deploy1=`git log -1 --pretty=%B`
    - echo "deploy1=$deploy1"
    - SUB=\(deploy\)
    - if [[ "$deploy1" == *"$SUB"* ]]; then deploy2="deploy"; else deploy2=""; fi
    - echo "deploy2=$deploy2"
    - if [ "$deploy2" !=  "" ]; then echo "OK"; ssh -p22 ababin464@35.209.102.231 'cd ~/work/admin-vue/; git add .; git stash; git checkout test; git pull; pm2 restart admin'; else echo "Not deploy"; fi

#      ssh -p22 ababin464@35.209.102.231 'echo "Congratulations! It is deploy";cd ~/work/admin-vue/; git add .; git stash; git checkout test; git pull; pm2 restart admin; else echo "Not deploy"; fi '


      #     - apk add --no-cache rsync openssh less
#    - mkdir -p ~/.ssh
#    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
##    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' >> ~/.ssh/id_rsa
##    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#    - chmod 700 ~/.ssh/id_rsa
##    - less ~/.ssh/id_rsa
#    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#    - ssh -p22 ababin464@35.209.102.231 "cd ~/work/admin-vue/ && gaa && git stash && gco test && gl && pm2 restart admin"
